### ISSUE TITLE
chromedriver slowness

### ISSUE THREAD

**Issue by otomay** [Xeo786/Rufaydium-Webdriver#25]
Only chromedriver has occasional slowdowns. I searched the internet and found that disabling the proxy might solve it [(here)](https://sqa.stackexchange.com/questions/13919/selenium-webdriver-for-chrome-too-slow). But I couldn't do it at Rufaydium. It's possible?

**Comment by Xeo786** [comment]
Can you please elaborate on what specific condition/occasion or reason chrome driver slowdowns?

Last tab/window close will close the session, When there are 2 webdriver Sessions and Session1 is closed by the user manually, not using Webdriver, webdriver will take time responding for accessing `Session2` because there are 2 sessions for Webdriver, session1 needed to be closed by webdriver side using `Session1.quit`, for smooth responses, But Rufaydium closes such session1 autonomously with one-time lag if method `GetSessionbyUrl()` or `GetSessionbyTitle()` used.

Best practice is to close session using Rufaydium

**Comment by otomay** [comment]
Thanks! I will try that.

It occasionally slow down while browsing, like infinite page loading. A behavior I haven't seen in firefox and edge. I couldn't trace a pattern, but I wasn't referring to when the user manually closes the session.
