### ISSUE TITLE
Can't get Edge driver to open Edge browser?

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#7]
The Chrome driver is working great, but when I try and use msedgedriver.exe instead, it still opens Chrome instead of Edge.

```
MSEdge := new Rufaydium("msedgedriver.exe","--port=9515")
```
Maybe I'm doing something wrong?

**Comment by Xeo786** [comment]
port 9515 is rufaydium default port and If you have running chromedriver.exe in background and its running with 9515 port,
Edge driver should be downloaded but would not we able to run due to occupied port, still Rufaydium will access 9515 which is already is use for chrome driver because its responding as expected because all browser has identical methods according to W3C  therefore you might having chrome browser controlled  instead of edge

What I thinking right now is.... to make Rufaydium intelligent enough so 
It can detect which driver is being run with what port if someone tell Rufaydium to run driver 
OR 
it checks driver if same driver is running with port in question, then its OK but it will throw error if you ask  different driver with a port but that port is already occupied with different driver
.....SO

Thank you so much for this inspiration
and sorry if that is not the case :(

**Comment by hotcheesesoup** [comment]
Ahhh! That driver persisting after closing the script is very interesting. I hadn't thought about elegantly ending it even though I'd read that part of the documentation. I'll need to add that into my script.

The newest build also has the new Capabilities.ahk which was messing me up. My existing `Chrome.capabilities := Capabilities.ChromeProfile` must have been interfering with it. I had to comment it out, and then it was able to open up in Edge instead. Nice!

Automatically downloading the "msedgedriver.exe" if it is missing doesn't seem to work right for me, but I'd already manually downloaded it.

Thanks!

**Comment by Xeo786** [comment]
Ok I would check Edge downloading why its not working...... 
We can exit driver manually by doing Session.Driver.Exit() but we will loose the control over all existing sessions created by driver, 
if driver is running in back ground we still has the ability to control then using GetSessionbyTitle() / GetSessionbyUrl(), read readme.md for examples
